# Generated by Django 3.1.2 on 2020-11-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cedar_app', '0002_auto_20201015_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='capture_search_2016',
            field=models.BooleanField(blank=True, help_text='Specifies whether the reference was captured in the 2016 literature search.', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='capture_search_2019',
            field=models.BooleanField(blank=True, help_text='Specifies whether the reference was captured in the 2019 literature search.', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='capture_snowball',
            field=models.BooleanField(blank=True, help_text='Specifies whether the reference was captured through snowballing (searching cited papers, and or reverse citations).', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='capture_submit',
            field=models.BooleanField(blank=True, help_text='Specifies whether the reference was captured through a direct submission to CEDAR.', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='exclude_extraction',
            field=models.BooleanField(blank=True, default=False, help_text='Specifies whether or not to exclude the reference from extraction.', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='other_reference_id',
            field=models.PositiveIntegerField(blank=True, help_text='An additional identifier for the reference, from the legacy database.', null=True, unique=True),
        ),
    ]
