# Generated by Django 3.1.2 on 2020-11-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cedar_app', '0003_auto_20201109_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='exclude_extraction',
            field=models.BooleanField(default=False, help_text='Specifies whether or not to exclude the reference from extraction.'),
        ),
    ]
