# Generated by Django 3.1.2 on 2020-11-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cedar_app', '0004_auto_20201109_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='name_bibtex',
            field=models.CharField(default='', help_text='An abbreviated identifier for the reference, given by Bibtex, i.e. "Jones2013"', max_length=200),
        ),
        migrations.AlterField(
            model_name='reference',
            name='study_title',
            field=models.TextField(default='', help_text='The title of the study, in sentence case.'),
        ),
    ]
