# Generated by Django 3.1.2 on 2021-01-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cedar_app', '0008_auto_20210108_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='ratetable_a',
            new_name='prevtable_a',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='ratetable_b',
            new_name='prevtable_b',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='ratetable_c',
            new_name='prevtable_c',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='ratetable_d',
            new_name='prevtable_d',
        ),
        migrations.AlterField(
            model_name='factor',
            name='odds_ratio_sig',
            field=models.CharField(blank=True, help_text='The significance (p-value) associated with the odds ratio that describes the factor, i.e. "< 0.05". May include symbols, numbers, and letters. There is no significance associated with count or prevalence data, only Odds Ratios. If an odds ratio is provided, without a significance level, please report "NR" for "not reported".', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location_join',
            name='ref_loc_note',
            field=models.TextField(blank=True, help_text='A free-text description of the subdivision, allowing users to specify custom subdivisions like "east", "Mid-atlantic region" or "Nationwide"', null=True),
        ),
    ]
