# Generated by Django 3.1.5 on 2021-02-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_cedar_app', '0016_auto_20210210_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atc_vet',
            old_name='levelname_4_simple',
            new_name='levelname_4_coarse',
        ),
        migrations.RenameField(
            model_name='factor_exclusion',
            old_name='factor',
            new_name='factor_id',
        ),
        migrations.RenameField(
            model_name='factor_exclusion',
            old_name='model',
            new_name='model_id',
        ),
        migrations.RenameField(
            model_name='location_join',
            old_name='loc_ref',
            new_name='loc_ref_id',
        ),
        migrations.RenameField(
            model_name='location_join',
            old_name='location_01',
            new_name='location_01_id',
        ),
        migrations.RenameField(
            model_name='location_join',
            old_name='location_02',
            new_name='location_02_id',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model_create_user',
            new_name='model_create_user_id',
        ),
        migrations.RenameField(
            model_name='reference_note',
            old_name='note_ref',
            new_name='note_ref_id',
        ),
        migrations.RenameField(
            model_name='reference_note',
            old_name='user',
            new_name='user_id',
        ),
    ]
