# Generated by Django 3.1.5 on 2021-02-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cedar_app', '0021_auto_20210210_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_02',
            name='DEP_sel_beef',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host_02',
            name='DEP_sel_broil',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='microbe_02',
            name='DEP_old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
