# Generated by Django 3.1.5 on 2021-02-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cedar_app', '0022_auto_20210210_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='CEDAR_extract_east',
            field=models.BooleanField(blank=True, default=True, help_text='Specifies whether this reference is to be extracted by the "east" team (i.e. Guelph/ON)', null=True),
        ),
    ]
