# Generated by Django 3.1.2 on 2020-10-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reference',
            name='archived_why',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
