# Generated by Django 4.2.1 on 2023-08-14 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res_outcome',
            name='ast_method',
            field=models.ForeignKey(blank=True, help_text='The AST method used to assay resistance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.ast_method'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='table_n_ab',
            field=models.PositiveIntegerField(blank=True, help_text='Missing Help Text', null=True),
        ),
    ]
