# Generated by Django 4.2.5 on 2024-06-27 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0003_alter_res_outcome_ast_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='ref_country',
            field=models.ForeignKey(help_text='Missing Help Text', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_01'),
        ),
    ]
