# Generated by Django 4.2.5 on 2024-06-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0004_alter_reference_ref_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='id_librarykey',
            field=models.CharField(default='', help_text='Missing Help Text', max_length=50),
        ),
        migrations.AddField(
            model_name='reference',
            name='id_submission',
            field=models.CharField(blank=True, default='', help_text='Missing Help Text', max_length=50),
        ),
    ]
