# Generated by Django 3.1.2 on 2020-12-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0006_auto_20201215_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location_join',
            old_name='note',
            new_name='ref_loc_note',
        ),
    ]
