# Generated by Django 3.1.5 on 2021-02-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0010_auto_20210111_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='reference',
            new_name='factor_ref',
        ),
        migrations.RenameField(
            model_name='location_join',
            old_name='reference',
            new_name='loc_ref',
        ),
        migrations.RenameField(
            model_name='reference_note',
            old_name='reference',
            new_name='note_ref',
        ),
        migrations.AlterField(
            model_name='host_01',
            name='host_name',
            field=models.CharField(help_text='The�host�from�which�the�assayed�microbe�originated,�i.e.�"Chicken"', max_length=20, unique=True),
        ),
    ]
