# Generated by Django 3.1.5 on 2021-02-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0012_auto_20210210_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='publish_name_alt',
            field=models.CharField(default='', max_length=500),
        ),
    ]
