# Generated by Django 3.1.5 on 2021-02-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0013_reference_publish_name_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='publish_name_alt',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
