# Generated by Django 3.1.5 on 2021-02-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0014_auto_20210210_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='study_objective',
            new_name='DEP_study_objective',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='ast_method',
            new_name='ast_method_id',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='name_bibtex',
            new_name='key_bibtex',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='ident_doi',
            new_name='publish_doi',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='publisher',
            new_name='publish_id',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='ident_pmid',
            new_name='publish_pmid',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='publication_year',
            new_name='publish_year',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='has_breakpoint',
            new_name='ref_has_explicit_break',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='has_mic_table',
            new_name='ref_has_mic_table',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='RWID',
            new_name='refwk',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='name_author',
            new_name='study_authors',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='study_design',
            new_name='study_design_id',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='v12_is_v1_import',
            new_name='v12_v1_id',
        ),
    ]
