# Generated by Django 3.1.5 on 2021-02-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0015_auto_20210210_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='factor_ref',
            new_name='factor_ref_id',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='host_01',
            new_name='host_01_id',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='host_02',
            new_name='host_02_id',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='microbe_01',
            new_name='microbe_01_id',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='microbe_02',
            new_name='microbe_02_id',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='moa_type',
            new_name='moa_type_id',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='moa_unit',
            new_name='moa_unit_id',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='prod_stage_group_allocate',
            new_name='prod_stage_group_allocate_id',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='prod_stage_group_observe',
            new_name='prod_stage_group_observe_id',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='resistance',
            new_name='resistance_id',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='v12_was_replaced',
            new_name='v12_solo_extraction_2016',
        ),
    ]
