# Generated by Django 3.1.5 on 2021-02-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0018_reference_dep_other_genomics'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='DEP_analysis_unit_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='DEP_ref_has_mdr',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No'), ('2', 'Unclear'), ('3', 'Not Reported'), ('4', 'Needs Review')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='OLD_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='OLD_countryID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='OLD_has_plasmid_type',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='OLD_pub_name',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='OLD_ref_has_wgs',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No'), ('2', 'Unclear'), ('3', 'Not Reported'), ('4', 'Needs Review')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='OLD_status_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='OLD_subdivision',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='ast_free',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='ref_has_data_geno_level',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No'), ('2', 'Unclear'), ('3', 'Not Reported'), ('4', 'Needs Review')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='ref_has_data_pheno_level',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No'), ('2', 'Unclear'), ('3', 'Not Reported'), ('4', 'Needs Review')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='ref_has_esbl_factor',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No'), ('2', 'Unclear'), ('3', 'Not Reported'), ('4', 'Needs Review')], max_length=2, null=True),
        ),
    ]
