# Generated by Django 3.1.5 on 2021-02-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0024_auto_20210211_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='CEDAR_extract_east',
            new_name='CEDAR_extract_east_test',
        ),
    ]
