# Generated by Django 3.1.5 on 2021-02-11 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0026_auto_20210211_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atc_vet',
            name='aro_number',
            field=models.IntegerField(blank=True, help_text="The preparation/gene's ARO number (from CARD).", null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='is_added',
            field=models.BooleanField(help_text='The preparation/gene was added by the CEDAR team, and is not reflected in the published ATCvet index.'),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='is_duplicate',
            field=models.BooleanField(help_text='There is another ATCvet code which include the same preparation(s). Use the alternate ATCvet code.'),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='is_gene',
            field=models.BooleanField(help_text='The preparation/gene is a gene.'),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelcode_1',
            field=models.CharField(blank=True, help_text="The portion of the ATCvet code that describes the preparation's anatomical group.", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelcode_2',
            field=models.CharField(blank=True, help_text="The portion of the ATCvet code that describes the preparation's therapeutic main group.", max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelcode_3',
            field=models.CharField(blank=True, help_text="The portion of the ATCvet code that describes the preparation's top-level therapeutic subgroup.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelcode_4',
            field=models.CharField(blank=True, help_text="The portion of the ATCvet code that describes the preparation's bottom-level therapeutic subgroup.", max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelcode_5',
            field=models.CharField(blank=True, help_text='The ATCvet code that describes the preparation.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_1',
            field=models.CharField(help_text='The anatomical group to which the preparation belongs.', max_length=100),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_2',
            field=models.CharField(blank=True, help_text='The therapeutic main group to which the preparation belongs.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_3',
            field=models.CharField(blank=True, help_text='The chemical/therapeutic/pharmacological subgroup (top-level) to which the preparation belongs.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_4',
            field=models.CharField(blank=True, help_text='The chemical/therapeutic/pharmacological subgroup (bottom-level) to which the preparation belongs.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_4_coarse',
            field=models.CharField(blank=True, help_text='A coarser classification at the fourth level (chemical/therapeutic/pharmacological subgroup) to simplify record retrieval.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_5',
            field=models.CharField(blank=True, help_text='The chemical substance in the preparation.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_5_alt',
            field=models.CharField(blank=True, help_text='An alternative name(s) for the preparation (e.g. USAN, BAN, ubiquitous priprietary name).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_5_comb_example',
            field=models.CharField(blank=True, help_text='An example of a specific combination-preparation representative of the generic combination represented in the ATCvet.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='host_01_id',
            field=models.ForeignKey(blank=True, help_text='The ID of the parent host', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.host_01'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='microbe_01_id',
            field=models.ForeignKey(blank=True, help_text='The ID of the parent microbe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.microbe_01'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='odds_ratio_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The level pertaining to the lower and upper confidence intervals (i.e. 95%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publish_name_alt',
            field=models.CharField(blank=True, default='', help_text='The name of the publisher as provided in the source material, if different than the publisher indicated by publish_id. ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_campylobacter',
            field=models.BooleanField(blank=True, help_text='The title or abstract of this reference contains keywords related to this topic (animal, or microbe).', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_cattle',
            field=models.BooleanField(blank=True, help_text='The title or abstract of this reference contains keywords related to this topic (animal, or microbe).', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_chicken',
            field=models.BooleanField(blank=True, help_text='The title or abstract of this reference contains keywords related to this topic (animal, or microbe).', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_ecoli',
            field=models.BooleanField(blank=True, help_text='The title or abstract of this reference contains keywords related to this topic (animal, or microbe).', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_enterococcus',
            field=models.BooleanField(blank=True, help_text='The title or abstract of this reference contains keywords related to this topic (animal, or microbe).', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_salmonella',
            field=models.BooleanField(blank=True, help_text='The title or abstract of this reference contains keywords related to this topic (animal, or microbe).', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_swine',
            field=models.BooleanField(blank=True, help_text='The title or abstract of this reference contains keywords related to this topic (animal, or microbe).', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_turkey',
            field=models.BooleanField(blank=True, help_text='The title or abstract of this reference contains keywords related to this topic (animal, or microbe).', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='v12_solo_extraction_2016',
            field=models.BooleanField(blank=True, help_text='The factor was replaced (sole source).', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='v12_v1_id',
            field=models.BooleanField(blank=True, help_text='The record was imported from CEDAR_v1 into CEDAR_v2.', null=True),
        ),
    ]
