# Generated by Django 3.1.7 on 2021-08-31 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0028_auto_20210831_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host_02',
            name='host_01_id',
        ),
        migrations.AddField(
            model_name='host_02',
            name='host_01_id',
            field=models.ForeignKey(blank=True, help_text='The ID of the parent host', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.host_01'),
        ),
        migrations.RemoveField(
            model_name='microbe_02',
            name='microbe_01_id',
        ),
        migrations.AddField(
            model_name='microbe_02',
            name='microbe_01_id',
            field=models.ForeignKey(blank=True, help_text='The ID of the parent microbe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.microbe_01'),
        ),
    ]
