# Generated by Django 3.1.7 on 2021-09-01 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0029_auto_20210831_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='cedar_exclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusion', models.CharField(blank=True, max_length=500, null=True)),
                ('exclusion_type', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='figure_extract_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('method_description', models.CharField(blank=True, max_length=500, null=True)),
                ('method_wpd', models.BooleanField(blank=True, null=True)),
                ('method_convert_to_count', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='factor_exclusion',
            old_name='factor_id',
            new_name='fk_factor_id',
        ),
        migrations.RenameField(
            model_name='factor_exclusion',
            old_name='model_id',
            new_name='fk_model_id',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='OLD_country_id',
            new_name='DEL_OLD_countryID',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='DEP_analysis_unit_id',
            new_name='DEP_analysis_unit_ID',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='OLD_status_id',
            new_name='OLD_status_ID',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='CEDAR_extract_esr',
            new_name='cedar_extract_esr',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='CEDAR_extract_east',
            new_name='dep_CEDAR_extract_east',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='CEDAR_extract_west',
            new_name='dep_CEDAR_extract_west',
        ),
        migrations.RenameField(
            model_name='reference_history_join',
            old_name='action',
            new_name='fk_reference_history_action_id',
        ),
        migrations.RenameField(
            model_name='reference_history_join',
            old_name='reference',
            new_name='fk_reference_id',
        ),
        migrations.RenameField(
            model_name='reference_history_join',
            old_name='user',
            new_name='fk_user_id',
        ),
        migrations.RenameField(
            model_name='reference_note',
            old_name='user_id',
            new_name='fk_user_id',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='exclude_is_validation',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='OLD_id',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='OLD_subdivision',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='topic_tab_has_topic',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='topic_tab_host_free',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='topic_tab_microbe_free',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='v12_reference_ID_in_v1',
        ),
        migrations.RemoveField(
            model_name='reference_history_action',
            name='action_level',
        ),
        migrations.RemoveField(
            model_name='reference_note',
            name='note_ref_id',
        ),
        migrations.RemoveField(
            model_name='res_outcome',
            name='fk_extract_user_id',
        ),
        migrations.AddField(
            model_name='factor_exclusion',
            name='T2_ID_alternate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host_01',
            name='cedar_esr_id',
            field=models.PositiveIntegerField(blank=True, help_text='The user in CEDAR ESR', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='legacy_user',
            name='cedar_esr_id',
            field=models.PositiveIntegerField(blank=True, help_text='The user in CEDAR ESR', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='microbe_02',
            name='cedar_esr_id',
            field=models.PositiveIntegerField(blank=True, help_text='The user in CEDAR ESR', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='production_stage',
            name='cedar_esr_id',
            field=models.PositiveIntegerField(blank=True, help_text='The user in CEDAR ESR', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='DEL_ID_study_location_01',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='DEL_journal_title',
            field=models.CharField(blank=True, help_text='"journal_title" was imported free text journal, all info copied.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='DEL_subdivision',
            field=models.CharField(blank=True, help_text='"OLD_subdivision": was imported free text, location_02, already importd.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='dep_old_id',
            field=models.IntegerField(blank=True, help_text='DEPRECIATED: Formerly "OLD_ID". Unclear which ID - likely V0', null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='dep_topic_tab_has_topic',
            field=models.BooleanField(blank=True, help_text='The title and abstract of this reference has been keyword-searched to identify putative topics', null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='dep_topic_tab_host_free',
            field=models.CharField(blank=True, help_text='A free-text description of the hosts identified through the title and abstract keyword-search', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='dep_topic_tab_microbe_free',
            field=models.CharField(blank=True, help_text='A description of the microbes identified through the title and abstract keyword-search', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='exclude_model',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='exclude_model_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='ref_has_ast_explicit_break',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='t2_ast_break',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='t2_ast_breakID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='v12_is_v1_import',
            field=models.BooleanField(blank=True, help_text='The factor is imported from v1.', null=True),
        ),
        migrations.AddField(
            model_name='reference_history_action',
            name='action_level_coarse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reference_history_action',
            name='action_level_coarse_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference_history_action',
            name='action_level_fine',
            field=models.CharField(blank=True, help_text='The resultant status level. This refers to how the factor can be used', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reference_history_join',
            name='is_cedar_esr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reference_note',
            name='fk_note_ref_id',
            field=models.ForeignKey(blank=True, help_text='The reference that this note refers to', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference', to_field='other_reference_id'),
        ),
        migrations.AddField(
            model_name='reference_note',
            name='is_apply_factor',
            field=models.BooleanField(default=False, help_text='The note relates to factor-level information, and should be included as a note with all factors'),
        ),
        migrations.AddField(
            model_name='res_outcome',
            name='breakpoint_explicit',
            field=models.CharField(blank=True, help_text='The breakpoint (if explicit, but not from standard breakpoint source).  This field is not necessary to complete if breakpoint source is true. Set to NA if not assessed. (RO Table)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='res_outcome',
            name='fk_ast_method_id',
            field=models.ForeignKey(blank=True, help_text='The AST method used to assay resistance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.ast_method'),
        ),
        migrations.AddField(
            model_name='res_outcome',
            name='fk_user_extract_id',
            field=models.ForeignKey(blank=True, help_text='The user that extracted the resistance outcome. This is a dupe of user_entry; we should decide which to use', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.legacy_user'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='exclude_cedar',
            field=models.BooleanField(blank=True, help_text='Exclude this factor from CEDAR and timber', null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='exclude_cedar_reason',
            field=models.CharField(blank=True, help_text='Reason for exclusion of factor from CEDAR and timber', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='ufid',
            field=models.PositiveIntegerField(blank=True, help_text='This is the canonical factor ID, or FID', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='v12_solo_extraction_2016',
            field=models.BooleanField(blank=True, help_text='These are v1 factors that were migrated to v2 references, that will not be dual extracted, as they were thoroughly reviewed by Ashley or Daniella in v1', null=True),
        ),
        migrations.AlterField(
            model_name='factor_exclusion',
            name='exclude_reason',
            field=models.TextField(blank=True, help_text='A reason why the factor should be excluded from the model', null=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='country_area',
            field=models.TextField(help_text='The country or area', unique=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='iso_country_code_1',
            field=models.IntegerField(blank=True, help_text='ISO country code (numerical): the country specified by the iso_3166-1_num code.', null=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='iso_country_code_2',
            field=models.CharField(blank=True, help_text='ISO country code (2 characters): the country specified by the iso_3166-1_alpha_2 code', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='iso_country_code_3',
            field=models.CharField(blank=True, help_text='ISO country code (3 characters): the country specified by the iso_3166-1_alpha_3 code', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='DEP_study_objective',
            field=models.TextField(blank=True, help_text='The stated objective of the resource', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='archived',
            field=models.BooleanField(blank=True, default=False, help_text='The reference is archived; it is not returned in queries or statistics', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='archived_why',
            field=models.CharField(blank=True, help_text='Why is the reference archived?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='exclude_extraction',
            field=models.BooleanField(default=False, help_text='Specifies whether or not to exclude the reference from extraction. If true, it is not returned in model-building queries or statistics.'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='exclude_extraction_reason',
            field=models.CharField(blank=True, help_text='If the reference is to be excluded, the reason for doing so', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='v12_solo_extraction_2016',
            field=models.BooleanField(blank=True, help_text='These are v1 factors that were migrated to v2 references, that will not be dual extracted, as they were thoroughly reviewed by Ashley or Daniella in v1', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='v12_v1_id',
            field=models.BooleanField(blank=True, help_text='The reference ID used within CEDAR v1. This only exists when the reference is an import from v1.', null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='contable_a',
            field=models.PositiveIntegerField(blank=True, help_text='The number (count) of observations of resistance in the exposed group', null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='contable_b',
            field=models.PositiveIntegerField(blank=True, help_text='The number (count) of observations of susceptibility in the exposed group', null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='contable_c',
            field=models.PositiveIntegerField(blank=True, help_text='The number (count) of observations of resistance in the referent group', null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='contable_d',
            field=models.PositiveIntegerField(blank=True, help_text='The number (count) of observations of susceptibility in the referent group', null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='extract_date',
            field=models.DateField(blank=True, help_text='The date at which the resistance outcome was extracted', null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='extract_version',
            field=models.PositiveIntegerField(blank=True, help_text='The version of the extraction; this is to supplement date, when we need a older extraction to be used.', null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='figure_extract',
            field=models.BooleanField(blank=True, help_text='True where the figure was extracted from a figure. This excludes cases where the figure is captioned with values', null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='figure_extract_reproducible',
            field=models.BooleanField(blank=True, help_text='True where a copy of the data extraction tool output is available', null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='fk_figure_extract_method_id',
            field=models.TextField(blank=True, help_text='The method used to extract the resistance outcome (RO) from the reference', null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='fk_genetic_element_id',
            field=models.ForeignKey(blank=True, help_text='The genomic resistance assayed as a measure of resistance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.genetic_element'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='fk_moa_type_id',
            field=models.ForeignKey(blank=True, help_text='The type of measure of association reported for the resistance outcome', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.moa_type'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='odds_ratio_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The confidence level associated with the confidence interval (as a percentage, most commonly 95%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='place_in_text',
            field=models.CharField(blank=True, help_text='The location of the resistance outcome data in-text, i.e. "Table 2". If the data is from the body of the text, use the page and paragraph numbers (Pg. and Para. respectively)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='urid',
            field=models.PositiveIntegerField(blank=True, help_text='The canonical resistance outcome ID. The OID is shared between resistance outcomes (ROs) that have been extracted in duplicate', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='fk_cedar_exclusion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.cedar_exclude'),
        ),
    ]
