# Generated by Django 3.1.7 on 2021-09-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0030_auto_20210901_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='factor_family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_family_name', models.CharField(blank=True, help_text='The factor family name', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='factor_parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_parent_name', models.CharField(blank=True, help_text='The parent factor name', max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='factor_exclusion',
            name='fk_factor_id',
            field=models.ForeignKey(blank=True, help_text='The factor identifier, or FID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor'),
        ),
        migrations.AlterField(
            model_name='reference_note',
            name='note',
            field=models.TextField(blank=True, help_text='Notes', null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='fk_figure_extract_method_id',
            field=models.ForeignKey(blank=True, help_text='The method used to extract the resistance outcome (RO) from the reference', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.figure_extract_method'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='fk_genetic_element_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.genetic_element'),
        ),
        migrations.CreateModel(
            name='factor_parent_join_factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_factor_id', models.ForeignKey(blank=True, help_text='The factor identifier, or FID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor')),
                ('fk_factor_parent_id', models.ForeignKey(blank=True, help_text='The parent factor identifier, or PFID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor_parent')),
            ],
        ),
        migrations.CreateModel(
            name='factor_parent_frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.DecimalField(blank=True, decimal_places=2, help_text='The frequency of factor implementation', max_digits=10, null=True)),
                ('frequency_distribution', models.CharField(blank=True, help_text='(optional) if a point value is not provided for frequency, a distribution name can be specified with parameters in other fields', max_length=200, null=True)),
                ('frequency_param_a', models.DecimalField(blank=True, decimal_places=2, help_text='First distribution parameter. Beta = a. Lower limit for uniform (i.e. range), pareto, triangular, etc.', max_digits=10, null=True)),
                ('frequency_param_b', models.DecimalField(blank=True, decimal_places=2, help_text='Second distribtuion parameter. Normal/log-normal = mean. Beta = b. Poisson = lambda. Mid or most-likely value for pareto, triangular, etc.', max_digits=10, null=True)),
                ('frequency_param_c', models.DecimalField(blank=True, decimal_places=2, help_text='Third distribution parameter. Normal/log-normal = SD/s, Upper limit for uniform (i.e. range), pareto, triangular, etc.', max_digits=10, null=True)),
                ('data_apply_start_year', models.IntegerField(blank=True, help_text='The first year this frequency applies to; if NULL, all years', null=True)),
                ('data_apply_end_year', models.IntegerField(blank=True, help_text='The last year this frequency applies to; if NULL, all years from start', null=True)),
                ('data_source', models.CharField(blank=True, help_text='The reference, or the person who provided the estimate', max_length=500, null=True)),
                ('data_source_added_year', models.IntegerField(blank=True, help_text='The year the reference was queried (if personal communication), or year published (if document)', null=True)),
                ('note', models.TextField(blank=True, help_text='Notes', null=True)),
                ('fk_factor_parent_id', models.ForeignKey(blank=True, help_text='The parent factor identifier, or PFID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor_parent')),
                ('fk_location_sub_id', models.ForeignKey(blank=True, help_text='The ID of the location from the location_02 table', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_02')),
                ('fk_user_entry_id', models.ForeignKey(blank=True, help_text='The user who added the frequency information', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_entry', to='cedar_core.legacy_user')),
                ('fk_user_review_id', models.ForeignKey(blank=True, help_text='The user who reviewed the frequency information', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_review', to='cedar_core.legacy_user')),
            ],
        ),
        migrations.CreateModel(
            name='factor_family_join_parent_factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_factor_family_id', models.ForeignKey(blank=True, help_text='The factor family identifier, or FFID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor_family')),
                ('fk_factor_parent_id', models.ForeignKey(blank=True, help_text='The parent factor identifier, or PFID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor_parent')),
            ],
        ),
    ]
