# Generated by Django 3.1.7 on 2021-09-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0031_auto_20210903_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='reference_join_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_loc_note', models.TextField(blank=True, help_text='A free-text description of the subdivision, allowing users to specify custom subdivisions like "east", "Mid-atlantic region" or "Nationwide"', null=True)),
                ('loc_ref_id', models.ForeignKey(blank=True, help_text='The reference pertaining to this location', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference', to_field='other_reference_id')),
                ('location_01_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_01')),
                ('location_02_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_02')),
            ],
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='fk_genetic_element_id',
            field=models.ForeignKey(blank=True, help_text='The genomic resistance assayed as a measure of resistance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.genetic_element'),
        ),
        migrations.DeleteModel(
            name='location_join',
        ),
    ]
