# Generated by Django 3.1.7 on 2021-09-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0032_auto_20210903_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reference_join_location',
        ),
    ]
