# Generated by Django 3.1.7 on 2021-09-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0033_delete_reference_join_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='reference_join_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_loc_note', models.TextField(blank=True, help_text='A free-text description of the subdivision, allowing users to specify custom subdivisions like "east", "Mid-atlantic region" or "Nationwide"', null=True)),
                ('loc_ref_id', models.ForeignKey(blank=True, help_text='The reference pertaining to this location', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference', to_field='other_reference_id')),
                ('location_01_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_01')),
                ('location_02_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_02')),
            ],
        ),
    ]
