# Generated by Django 3.1.7 on 2021-09-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0034_reference_join_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference_join_location',
            old_name='location_01_id',
            new_name='fk_location_01_id',
        ),
        migrations.RenameField(
            model_name='reference_join_location',
            old_name='location_02_id',
            new_name='fk_location_02_id',
        ),
        migrations.RenameField(
            model_name='reference_join_location',
            old_name='loc_ref_id',
            new_name='fk_reference_id',
        ),
        migrations.AlterField(
            model_name='factor',
            name='fk_reference_id',
            field=models.ForeignKey(help_text='The reference pertaining to this location', on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference', to_field='other_reference_id'),
        ),
    ]
