# Generated by Django 3.1.7 on 2021-09-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0035_auto_20210903_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='ast_breakpoint_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ast_breakpoint_std', models.CharField(blank=True, max_length=200, null=True)),
                ('ast_breakpoint_std_acronym', models.CharField(blank=True, max_length=200, null=True)),
                ('ast_breakpoint_std_accno', models.CharField(blank=True, max_length=200, null=True)),
                ('ast_breakpoint_std_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ast_breakpoint_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publish', models.CharField(blank=True, max_length=200, null=True)),
                ('date_last_valid', models.CharField(blank=True, max_length=200, null=True)),
                ('ast_breakpoint_std', models.CharField(blank=True, max_length=200, null=True)),
                ('ast_breakpoint_version', models.CharField(blank=True, max_length=200, null=True)),
                ('clsi_std_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
