# Generated by Django 3.1.7 on 2021-09-08 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0036_ast_breakpoint_source_ast_breakpoint_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='evidence_type_quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence_type_accno', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence_type_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='breakpoint_explicit',
            field=models.CharField(blank=True, help_text='The breakpoint (if explicit, but not from standard breakpoint source).  This field is not necessary to complete if breakpoint source is true. Set to NA if not assessed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='extract_version',
            field=models.PositiveIntegerField(blank=True, help_text='The version of the extraction; this is to supplement date, when we need a older extraction to be used', null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='fk_user_extract_id',
            field=models.ForeignKey(blank=True, help_text='The user that extracted the resistance outcome', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.legacy_user'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='urid',
            field=models.PositiveIntegerField(blank=True, help_text='The canonical resistance outcome ID. The URID is shared between resistance outcomes (ROs) that have been extracted in duplicate', null=True, unique=True),
        ),
    ]
