# Generated by Django 3.1.7 on 2021-09-08 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0037_auto_20210908_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor_parent_frequency',
            old_name='data_apply_end_year',
            new_name='frequency_data_apply_end_year',
        ),
        migrations.RenameField(
            model_name='factor_parent_frequency',
            old_name='data_apply_start_year',
            new_name='frequency_data_apply_start_year',
        ),
        migrations.RenameField(
            model_name='factor_parent_frequency',
            old_name='data_source',
            new_name='frequency_data_source',
        ),
        migrations.RenameField(
            model_name='factor_parent_frequency',
            old_name='data_source_added_year',
            new_name='frequency_data_source_added_year',
        ),
        migrations.AddField(
            model_name='factor_parent_frequency',
            name='fk_evidence_type_quality_frequency_id',
            field=models.ForeignKey(blank=True, help_text='The reference or source type ID, as an estimation of source quality (e.g. personal communication, surveillence, small study)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.evidence_type_quality'),
        ),
    ]
