# Generated by Django 3.1.7 on 2021-09-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0038_auto_20210908_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='fk_group_allocate_prod_stage_id',
            new_name='fk_production_stage_group_allocate_id',
        ),
        migrations.RenameField(
            model_name='res_outcome',
            old_name='fk_group_observe_prod_stage_id',
            new_name='fk_production_stage_group_observe_id',
        ),
    ]
