# Generated by Django 3.1.7 on 2021-09-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0039_auto_20210909_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='factor_parent_frequency',
        ),
    ]
