# Generated by Django 3.1.7 on 2021-09-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0041_factor_parent_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='res_outcome',
            old_name='extract_date',
            new_name='extract_date_ro',
        ),
        migrations.RenameField(
            model_name='res_outcome',
            old_name='extract_version',
            new_name='extract_version_ro',
        ),
        migrations.RenameField(
            model_name='res_outcome',
            old_name='extraction_num',
            new_name='extraction_num_ro',
        ),
        migrations.RenameField(
            model_name='res_outcome',
            old_name='fk_user_extract_id',
            new_name='fk_user_extract_ro_id',
        ),
        migrations.AddField(
            model_name='factor',
            name='extract_date_factor',
            field=models.DateField(blank=True, help_text='The date at which the resistance outcome was extracted', null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='extract_version_factor',
            field=models.PositiveIntegerField(blank=True, help_text='The version of the extraction; this is to supplement date, when we need a older extraction to be used', null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='extraction_num_factor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factor',
            name='fk_user_extract_factor_id',
            field=models.ForeignKey(blank=True, help_text='The user that extracted the resistance outcome', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.legacy_user'),
        ),
    ]
