# Generated by Django 3.1.7 on 2021-09-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0042_auto_20210909_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ro_factor_join',
        ),
    ]
