# Generated by Django 3.1.7 on 2021-09-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0043_delete_ro_factor_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='factor_join_res_outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_factor_id', models.ForeignKey(blank=True, help_text='The factor identifier, or FID', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor')),
                ('fk_res_outcome_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.res_outcome')),
            ],
        ),
    ]
