# Generated by Django 3.1.7 on 2021-09-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0046_reference_join_reference_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='factor_exclusion',
        ),
    ]
