# Generated by Django 3.1.7 on 2021-09-09 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0047_delete_factor_exclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor_family_join_parent_factor',
            name='fk_factor_parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor_parent'),
        ),
        migrations.AlterField(
            model_name='factor_parent_join_factor',
            name='fk_factor_parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor_parent'),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='fk_factor_parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor_parent'),
        ),
        migrations.CreateModel(
            name='factor_parent_join_atc_vet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_atc_vet_amu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.atc_vet')),
                ('fk_factor_parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor_parent')),
            ],
        ),
    ]
