# Generated by Django 3.1.7 on 2021-09-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0049_auto_20210910_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legacy_user',
            old_name='cedar_esr_id',
            new_name='cedar_esr_user_id',
        ),
        migrations.RemoveField(
            model_name='host_01',
            name='cedar_esr_id',
        ),
        migrations.RemoveField(
            model_name='microbe_02',
            name='cedar_esr_id',
        ),
        migrations.RemoveField(
            model_name='production_stage',
            name='cedar_esr_id',
        ),
        migrations.AddField(
            model_name='host_01',
            name='cedar_esr_host_01_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='microbe_02',
            name='cedar_esr_microbe_02_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='production_stage',
            name='cedar_esr_production_stage_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
