# Generated by Django 3.1.7 on 2021-09-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0050_auto_20210910_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor_parent_join_atc_vet',
            old_name='fk_factor_parent_id',
            new_name='fk_factor_parent_fp_join_av_id',
        ),
        migrations.RenameField(
            model_name='factor_parent_join_factor',
            old_name='fk_factor_id',
            new_name='fk_factor_fp_join_f_id',
        ),
        migrations.RenameField(
            model_name='reference_history_join',
            old_name='fk_reference_id',
            new_name='fk_reference_r_join_rh_id',
        ),
        migrations.RenameField(
            model_name='reference_history_join',
            old_name='fk_user_id',
            new_name='fk_user_r_join_rh_id',
        ),
        migrations.RenameField(
            model_name='reference_join_location',
            old_name='fk_reference_id',
            new_name='fk_reference_r_join_loc_id',
        ),
        migrations.RenameField(
            model_name='reference_join_reference_note',
            old_name='fk_user_id',
            new_name='fk_user_r_join_rn_id',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='fk_reference_id',
        ),
        migrations.RemoveField(
            model_name='factor_family_join_parent_factor',
            name='fk_factor_parent_id',
        ),
        migrations.RemoveField(
            model_name='factor_join_res_outcome',
            name='fk_factor_id',
        ),
        migrations.RemoveField(
            model_name='factor_parent_join_factor',
            name='fk_factor_parent_id',
        ),
        migrations.RemoveField(
            model_name='factor_parent_metadata',
            name='fk_factor_parent_id',
        ),
        migrations.AddField(
            model_name='factor',
            name='fk_reference_factor_id',
            field=models.ForeignKey(blank=True, help_text='The reference that describes the factor', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference', to_field='other_reference_id'),
        ),
        migrations.AddField(
            model_name='factor_family_join_parent_factor',
            name='fk_factor_parent_ff_join_pf_id',
            field=models.ForeignKey(blank=True, help_text='The parent factor identifier, or PFID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor_parent'),
        ),
        migrations.AddField(
            model_name='factor_join_res_outcome',
            name='fk_factor_f_join_ro_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor'),
        ),
        migrations.AddField(
            model_name='factor_parent_join_factor',
            name='fk_factor_parent_fp_join_f_id',
            field=models.ForeignKey(blank=True, help_text='The parent factor identifier, or PFID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor_parent'),
        ),
        migrations.AddField(
            model_name='factor_parent_metadata',
            name='fk_factor_parent_fp_metadata_id',
            field=models.ForeignKey(blank=True, help_text='The parent factor identifier, or PFID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor_parent'),
        ),
    ]
