# Generated by Django 3.1.7 on 2021-09-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0051_auto_20210910_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='res_outcome',
            old_name='fk_resistance_id',
            new_name='fk_atc_vet_resistance_id',
        ),
    ]
