# Generated by Django 3.1.7 on 2021-09-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0052_auto_20210910_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference_join_reference_note',
            old_name='fk_note_ref_id',
            new_name='fk_reference_r_join_rn_id',
        ),
    ]
