# Generated by Django 3.1.7 on 2021-09-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0054_delete_reference_history_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='reference_join_reference_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField(blank=True, null=True)),
                ('is_cedar_esr', models.BooleanField(default=False)),
                ('fk_reference_history_action_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.reference_history_action')),
                ('fk_reference_r_join_rh_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference', to_field='other_reference_id')),
                ('fk_user_r_join_rh_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.legacy_user')),
            ],
        ),
    ]
