# Generated by Django 3.1.7 on 2021-09-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0055_reference_join_reference_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='fk_host_01_id',
            new_name='fk_host_01_factor_id',
        ),
    ]
