# Generated by Django 3.1.7 on 2021-09-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0056_auto_20210910_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='fk_host_02_id',
        ),
        migrations.DeleteModel(
            name='host_02',
        ),
    ]
