# Generated by Django 3.1.7 on 2021-09-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0057_auto_20210910_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='host_02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_subtype_name', models.CharField(help_text='The host subtype from which the assayed microbe originated, i.e. "Eggs" for a parent host "Chicken"', max_length=100)),
                ('DEP_sel_beef', models.BooleanField(blank=True, null=True)),
                ('DEP_sel_broil', models.BooleanField(blank=True, null=True)),
                ('fk_host_01_host_02_id', models.ForeignKey(blank=True, help_text='The ID of the parent host', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.host_01')),
            ],
        ),
        migrations.AddField(
            model_name='factor',
            name='fk_host_02_id',
            field=models.ForeignKey(blank=True, help_text='The host subtype from which the microbe was isolated', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.host_02'),
        ),
    ]
