# Generated by Django 3.1.7 on 2021-09-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0058_auto_20210910_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='res_outcome',
            name='fk_microbe_02_id',
        ),
        migrations.DeleteModel(
            name='microbe_02',
        ),
    ]
