# Generated by Django 3.1.7 on 2021-09-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0059_auto_20210910_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='microbe_02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microbe_subtype_name', models.CharField(help_text='The species or subtype of the microbe subjected to AST, i.e. "coli" for parent microbe "Escherichia"', max_length=100)),
                ('DEP_old_id', models.IntegerField(blank=True, null=True)),
                ('cedar_esr_microbe_02_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('fk_microbe_01_id', models.ForeignKey(blank=True, help_text='The microbe assayed for resistance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.microbe_01')),
            ],
        ),
        migrations.AddField(
            model_name='res_outcome',
            name='fk_microbe_02_id',
            field=models.ForeignKey(blank=True, help_text='The subtype of the microbe assayed for resistance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.microbe_02'),
        ),
    ]
