# Generated by Django 3.1.7 on 2021-09-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0060_auto_20210910_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='res_outcome',
            old_name='fk_microbe_02_id',
            new_name='fk_microbe_02_res_outcome_id',
        ),
        migrations.RemoveField(
            model_name='microbe_02',
            name='fk_microbe_01_id',
        ),
        migrations.AddField(
            model_name='microbe_02',
            name='fk_microbe_01_microbe_02_id',
            field=models.ForeignKey(blank=True, help_text='The ID of the parent microbe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.microbe_01'),
        ),
    ]
