# Generated by Django 3.1.7 on 2021-09-10 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0061_auto_20210910_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor_parent_metadata',
            old_name='fk_location_sub_id',
            new_name='fk_location_02_fp_metadata_id',
        ),
        migrations.RenameField(
            model_name='genetic_element',
            old_name='element_accession_no',
            new_name='element_accno',
        ),
        migrations.RenameField(
            model_name='genetic_element',
            old_name='element_family_accession_no',
            new_name='element_family_accno',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model_create_user_id',
            new_name='fk_user_model_create_id',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model_maintain_user_id',
            new_name='fk_user_model_maintain_id',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='fk_cedar_exclusion_id',
            new_name='fk_cedar_exclude_id',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='publish_id',
            new_name='fk_publisher_id',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='study_design_id',
            new_name='fk_study_design_id',
        ),
        migrations.RenameField(
            model_name='reference_join_location',
            old_name='fk_location_02_id',
            new_name='fk_location_02_r_join_loc_id',
        ),
        migrations.RenameField(
            model_name='res_outcome',
            old_name='fk_ufid',
            new_name='fk_factor_ufid',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='ast_method_id',
        ),
        migrations.AddField(
            model_name='reference',
            name='fk_ast_method_id',
            field=models.ForeignKey(blank=True, help_text='The AST method used to assay resistance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.ast_method'),
        ),
    ]
