# Generated by Django 3.1.7 on 2021-09-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0062_auto_20210910_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='cedar_extract_turkey_update',
            field=models.BooleanField(blank=True, help_text='True if identified by the August 2021 update to the search (focused on turkeys only)', null=True),
        ),
        migrations.AlterField(
            model_name='factor_family_join_parent_factor',
            name='fk_factor_family_id',
            field=models.ForeignKey(blank=True, help_text='The factor family identifier, or FFID', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor_family'),
        ),
        migrations.AlterField(
            model_name='factor_family_join_parent_factor',
            name='fk_factor_parent_ff_join_pf_id',
            field=models.ForeignKey(blank=True, help_text='The parent factor identifier, or PFID', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor_parent'),
        ),
        migrations.AlterField(
            model_name='factor_join_res_outcome',
            name='fk_res_outcome_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.res_outcome'),
        ),
        migrations.AlterField(
            model_name='factor_parent_join_atc_vet',
            name='fk_factor_parent_fp_join_av_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor_parent'),
        ),
        migrations.AlterField(
            model_name='factor_parent_join_factor',
            name='fk_factor_fp_join_f_id',
            field=models.ForeignKey(blank=True, help_text='The factor identifier, or FID', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor'),
        ),
        migrations.AlterField(
            model_name='factor_parent_join_factor',
            name='fk_factor_parent_fp_join_f_id',
            field=models.ForeignKey(blank=True, help_text='The parent factor identifier, or PFID', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor_parent'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='fk_factor_ufid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor', to_field='ufid'),
        ),
    ]
