# Generated by Django 3.1.7 on 2021-10-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0064_auto_20210922_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='OLD_pub_name',
        ),
        migrations.AddField(
            model_name='reference',
            name='DEP_ID_study_location_01_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_has_ast_explicit_break',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No'), ('2', 'Unclear'), ('3', 'Not Reported'), ('4', 'Needs Review')], help_text='Specifies whether the study explicitly reports the MIC values used in its susceptibility tests', max_length=2, null=True),
        ),
    ]
