# Generated by Django 3.1.7 on 2021-10-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0065_auto_20211012_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='fk_factor_reference_id',
            field=models.ForeignKey(blank=True, help_text='The reference that describes the factor', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference'),
        ),
        migrations.AlterField(
            model_name='reference_join_location',
            name='fk_reference_join_location_reference_id',
            field=models.ForeignKey(blank=True, help_text='The reference pertaining to this location', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference'),
        ),
        migrations.AlterField(
            model_name='reference_join_reference_history',
            name='fk_reference_join_history_reference_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference'),
        ),
        migrations.AlterField(
            model_name='reference_join_reference_note',
            name='fk_reference_join_note_reference_id',
            field=models.ForeignKey(blank=True, help_text='The reference that this note refers to', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference'),
        ),
    ]
