# Generated by Django 3.1.7 on 2021-10-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0066_auto_20211012_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='extraction_num_factor',
        ),
        migrations.RemoveField(
            model_name='res_outcome',
            name='extraction_num_ro',
        ),
    ]
