# Generated by Django 3.1.7 on 2021-10-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0068_auto_20211013_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='res_outcome',
            name='fk_factor_ufid',
        ),
        migrations.AddField(
            model_name='res_outcome',
            name='fk_factor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor'),
        ),
    ]
