# Generated by Django 3.1.7 on 2021-10-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0069_auto_20211019_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='res_outcome',
            name='fk_ast_breakpoint_source_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.ast_breakpoint_source'),
        ),
    ]
