# Generated by Django 3.1.7 on 2021-10-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0070_res_outcome_fk_ast_breakpoint_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='ufid',
            field=models.PositiveIntegerField(blank=True, help_text='This is the canonical factor ID, or FID', null=True),
        ),
    ]
