# Generated by Django 3.1.7 on 2021-10-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0072_auto_20211020_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='extract_version_factor',
        ),
        migrations.RemoveField(
            model_name='res_outcome',
            name='extract_version_ro',
        ),
    ]
