# Generated by Django 3.1.7 on 2022-03-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0073_auto_20211022_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='ufid',
            new_name='sfid',
        ),
        migrations.RenameField(
            model_name='res_outcome',
            old_name='urid',
            new_name='soid',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='exclude_cedar_reason',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='extract_date_factor',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='fk_extract_factor_user_id',
        ),
    ]
