# Generated by Django 3.1.7 on 2022-03-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0074_auto_20220303_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='res_outcome',
            name='DEP_exclude_iam',
        ),
        migrations.RemoveField(
            model_name='res_outcome',
            name='DEP_exclude_iam_reason',
        ),
        migrations.RemoveField(
            model_name='res_outcome',
            name='DEP_total_obs',
        ),
        migrations.RemoveField(
            model_name='res_outcome',
            name='OLD_resistance_id',
        ),
        migrations.RemoveField(
            model_name='res_outcome',
            name='OLD_short_name',
        ),
        migrations.RemoveField(
            model_name='res_outcome',
            name='OLD_use_id',
        ),
        migrations.RemoveField(
            model_name='res_outcome',
            name='TEMP_use_id',
        ),
        migrations.RemoveField(
            model_name='res_outcome',
            name='microbe_02_old_id',
        ),
    ]
