# Generated by Django 3.1.7 on 2022-03-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0075_auto_20220303_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='fk_factor_reference_id',
            field=models.ForeignKey(default=99999, help_text='The reference that describes the factor', on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference'),
        ),
    ]
