# Generated by Django 3.1.7 on 2022-03-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0076_auto_20220304_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='DEL_ID_study_location_01',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='DEL_OLD_countryID',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='DEL_journal_title',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='DEL_subdivision',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='DEP_ID_study_location_01_num',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='DEP_analysis_unit_ID',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='DEP_other_genomics',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='DEP_ref_has_mdr',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='DEP_study_objective',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='OLD_has_plasmid_type',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='OLD_ref_has_wgs',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='OLD_status_ID',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='dep_old_id',
        ),
    ]
