# Generated by Django 3.1.7 on 2022-03-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0079_auto_20220308_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference_join_reference_history',
            name='fk_reference_join_history_reference_id',
        ),
        migrations.AddField(
            model_name='reference_join_reference_history',
            name='reference_join_history_reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
