# Generated by Django 3.1.7 on 2022-03-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0081_auto_20220308_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_join_reference_history',
            name='action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
