# Generated by Django 3.1.7 on 2022-03-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0082_auto_20220308_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_join_reference_history',
            name='reference_join_history_reference_id',
            field=models.IntegerField(blank=True, help_text="The reference ID corresponding to this history entry. This was formerly a foreign key to the reference table. Since the reference table now has a foreign key for this table's primary id instead, the former foreign key to the reference table can no longer exist. Now that this reference_join_reference_history table is depreciated (purely a legacy table), the foreign key to the reference table is not necessary anyway.", null=True),
        ),
    ]
