# Generated by Django 3.1.7 on 2022-03-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0083_auto_20220308_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='other_reference_id',
        ),
    ]
