# Generated by Django 3.1.7 on 2022-03-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0084_remove_reference_other_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='dep_CEDAR_extract_east',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='dep_CEDAR_extract_west',
        ),
    ]
