# Generated by Django 3.1.7 on 2022-03-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0085_auto_20220308_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='fk_reference_status_id',
            field=models.IntegerField(blank=True, help_text='The foreign key from the reference_status table. This is being implemented in v3 (CEDAR Web).', null=True),
        ),
    ]
