# Generated by Django 3.1.7 on 2022-03-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0086_reference_fk_reference_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='study_location_01_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
