# Generated by Django 3.1.7 on 2022-03-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0087_reference_study_location_01_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='exclude_extraction_reason',
            field=models.TextField(blank=True, help_text='If the reference is to be excluded, the reason for doing so', null=True),
        ),
    ]
