# Generated by Django 3.1.7 on 2022-03-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0088_auto_20220311_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='v12_v1_id',
            field=models.PositiveIntegerField(blank=True, help_text='The reference ID used within CEDAR v1. This only exists when the reference is an import from v1.', null=True),
        ),
    ]
