# Generated by Django 3.1.7 on 2022-03-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0089_auto_20220317_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='factor_title',
            field=models.TextField(blank=True, help_text='A title that describes the factor, in title case. The title should be simple and direct, with no experimental context. The goal is to be able to understand what the factor is, while leaving the name as generic as possible; comparable factors from different studies should be easily indentifiable as comparable. Common abbreviations are acceptable. Factors including antimicrobial use should be formatted as "AntiX Use" where AntiX is the antimicrobial(s) administered (e.g. Bambermycin Use, Ceftiofur Use). Factors comparing organic / no antimicrobial use / free-range / conventional production should be titled "Production Type", and a precise description provided in the description field', null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='group_exposed',
            field=models.TextField(blank=True, help_text='A brief description of the exposed group, in title case. The description should again, be simple and direct.  Comparison groups are allocated as described in the literature. If no allocation is provided, the less interventionist (or default practice) should be used as the referent. Factors including antimicrobial use are always given with the less interventionist as the referent (i.e. with "No Use" as the referent group or the lower dose as the referent, and "AntiX Use" for the exposed group,  where AntiX is the antimicrobial(s) administered). The dose should be provided in the main factor description, unless the factor is a comparison of two doses', null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='group_referent',
            field=models.TextField(blank=True, help_text='A brief description of the referent (unexposed) group, in title case. The description should again, be simple and direct. Comparison groups are allocated as described in the literature. If no allocation is provided, the less interventionist (or default practice) should be used as the referent. Factors including antimicrobial use are always given with the less interventionist as the referent (i.e. with "No Use" as the referent group or the lower dose as the referent, and "AntiX Use" for the exposed group,  where AntiX is the antimicrobial(s) administered). The dose should be provided in the main factor description, unless the factor is a comparison of two doses', null=True),
        ),
    ]
