# Generated by Django 3.1.7 on 2022-03-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0092_auto_20220318_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='cedar_extract_esr',
            field=models.BooleanField(blank=True, help_text='Specifies whether this reference was extracted by the ESR team (i.e. "Enterococcus Scoping Review"). References marked cedar_extract_esr = TRUE were either: a) identified by both the ESR and the 2019 literature search (and extracted by the ESR team) or b) identified by the ESR only.', null=True),
        ),
    ]
