# Generated by Django 3.1.7 on 2022-03-29 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0098_auto_20220328_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res_outcome',
            name='extract_date_ro',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date at which the resistance outcome was extracted'),
        ),
    ]
