# Generated by Django 4.0.4 on 2022-05-29 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0099_auto_20220328_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_02',
            name='fk_location_02_location_01_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_01', to_field='iso_country_code_2'),
        ),
        migrations.AlterField(
            model_name='location_02',
            name='subdivision_code',
            field=models.CharField(max_length=3),
        ),
        migrations.CreateModel(
            name='location_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision_type', models.CharField(blank=True, help_text='The type of subdivision within the country, i.e. "Province"', max_length=100, null=True)),
                ('subdivision', models.CharField(help_text='The name of the subdivision, i.e. "Ontario"', max_length=100)),
                ('iso_3166_2', models.CharField(help_text='The subdivision code specified by the iso_3166_2 code. Normally two or three letters (i.e. "ON" for Ontario), but the numerals 2-9 may also be used', max_length=3)),
                ('cipars_region_national', models.BooleanField(help_text='The location is within the CIPARS national region')),
                ('cipars_region_atlantic', models.BooleanField(help_text='The location is within the CIPARS atlantic region')),
                ('cipars_region_maritimes', models.BooleanField(help_text='The location is within the CIPARS maritimes region')),
                ('cipars_region_prairies', models.BooleanField(help_text='The location is within the CIPARS prairies region')),
                ('iso_3166_1_alpha2', models.ForeignKey(help_text='The ISO 3166 alpha-2 country code, i.e. "CA" for Canada', on_delete=django.db.models.deletion.DO_NOTHING, to='cedar_core.location_01', to_field='iso_country_code_2')),
            ],
        ),
    ]
