# Generated by Django 4.0.4 on 2022-05-29 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0101_alter_location_sub_iso_3166_1_alpha2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location_01',
            old_name='bin_developing',
            new_name='is_developing',
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='bin_land_lock_least_developed_countries',
            new_name='is_land_lock_least_developed_countries',
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='bin_least_developed_countries',
            new_name='is_least_developed_countries',
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='bin_small_island_developing_states',
            new_name='is_small_island_developing_states',
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='iso_country_code_2',
            new_name='iso_3166_1_alpha2',
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='code_intermediate_subregion',
            new_name='loc_intermediate_subregion_code',
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='name_intermediate_subregion',
            new_name='loc_intermediate_subregion_name',
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='code_region',
            new_name='loc_region_code',
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='name_region',
            new_name='loc_region_name',
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='code_subregion',
            new_name='loc_subregion_code',
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='name_subregion',
            new_name='loc_subregion_name',
        ),
        migrations.RemoveField(
            model_name='location_01',
            name='code_global',
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='country_area',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='iso_country_code_1',
            new_name='iso_3166_1_numeric'
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='iso_country_code_3',
            new_name='iso_3166_1_alpha3',
        ),
        migrations.RenameField(
            model_name='location_01',
            old_name='m49_code',
            new_name='m49',
        ),
        migrations.RemoveField(
            model_name='location_01',
            name='name_global',
        ),
        migrations.AlterField(
            model_name='location_02',
            name='fk_location_02_location_01_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cedar_core.location_01', to_field='iso_3166_1_alpha2'),
        ),
    ]
