# Generated by Django 4.0.4 on 2022-05-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0102_rename_bin_developing_location_01_is_developing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_01',
            name='country',
            field=models.CharField(default='N/A', help_text='The country or area', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='iso_3166_1_alpha3',
            field=models.CharField(blank=True, help_text='ISO country code (3 characters): the country specified by the iso_3166-1_alpha_3 code', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='iso_3166_1_numeric',
            field=models.IntegerField(blank=True, help_text='ISO country code (numerical): the country specified by the iso_3166-1_num code.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='m49',
            field=models.IntegerField(blank=True, help_text='M49 code', null=True, unique=True),
        ),
    ]
