# Generated by Django 4.0.4 on 2022-05-29 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0103_alter_location_01_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference_join_location',
            name='fk_location_01_id',
        ),
        migrations.RemoveField(
            model_name='reference_join_location',
            name='fk_reference_join_location_location_02_id',
        ),
        migrations.RemoveField(
            model_name='reference_join_location',
            name='fk_reference_join_location_reference_id',
        ),
        migrations.RemoveField(
            model_name='reference_join_location',
            name='ref_loc_note',
        ),
        migrations.AddField(
            model_name='reference_join_location',
            name='location_detail',
            field=models.TextField(blank=True, help_text='A free-text description of the subdivision, allowing users to specify custom subdivisions like "east", "Mid-atlantic region" or "Nationwide"'),
        ),
        migrations.AddField(
            model_name='reference_join_location',
            name='location_main_id',
            field=models.ForeignKey(blank=True, db_column='location_main_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_01'),
        ),
        migrations.AddField(
            model_name='reference_join_location',
            name='location_sub_id',
            field=models.ForeignKey(blank=True, db_column='location_sub_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_02'),
        ),
        migrations.AddField(
            model_name='reference_join_location',
            name='reference_id',
            field=models.ForeignKey(blank=True, db_column='reference_id', help_text='The reference pertaining to this location', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference'),
        ),
    ]
