# Generated by Django 4.0.4 on 2022-05-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0104_remove_reference_join_location_fk_location_01_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference_join_location',
            name='location_alpha3_dep',
            field=models.TextField(blank=True, null=True),
        ),
    ]
