# Generated by Django 4.0.4 on 2022-05-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0105_reference_join_location_location_alpha3_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_join_location',
            name='location_detail',
            field=models.TextField(blank=True, help_text='A free-text description of the subdivision, allowing users to specify custom subdivisions like "east", "Mid-atlantic region" or "Nationwide"', null=True),
        ),
    ]
