# Generated by Django 4.0.4 on 2022-05-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0106_alter_reference_join_location_location_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_join_location',
            name='location_sub_id',
            field=models.ForeignKey(blank=True, db_column='location_sub_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_sub'),
        ),
    ]
