# Generated by Django 4.0.4 on 2022-05-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0107_alter_reference_join_location_location_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='HIST_ESR_host_01_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
