# Generated by Django 4.0.4 on 2022-05-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0108_factor_hist_esr_host_01_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_02',
            name='is_prod_stream_beef',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='production_stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_stream_name', models.CharField(max_length=100)),
                ('host_main_id', models.ForeignKey(db_column='host_main_id', on_delete=django.db.models.deletion.CASCADE, to='cedar_core.host_01')),
            ],
        ),
    ]
