# Generated by Django 4.0.4 on 2022-05-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0110_remove_production_stream_host_main_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_stream',
            name='host_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cedar_core.host_01'),
        ),
    ]
