# Generated by Django 4.0.4 on 2022-05-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0113_alter_production_stream_host_subs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host_02',
            name='is_prod_stream_beef',
        ),
        migrations.AddField(
            model_name='host_02',
            name='HIST_host_01_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
