# Generated by Django 4.0.4 on 2022-05-29 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0114_remove_host_02_is_prod_stream_beef_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host_02',
            old_name='fk_host_02_host_01_id',
            new_name='host_01'
        )
    ]
