# Generated by Django 4.0.4 on 2022-05-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0116_alter_host_02_host_01'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='study_authors',
            new_name='ref_author',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='study_title',
            new_name='ref_title',
        ),
    ]
