# Generated by Django 4.0.4 on 2022-05-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0117_rename_study_authors_reference_ref_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='ref_abstract',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
