# Generated by Django 4.0.4 on 2022-05-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0119_alter_reference_ref_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='study_design_detail',
            field=models.TextField(blank=True, default='', help_text='The details of the study design. Often, this can be copied from the study directly'),
            preserve_default=False,
        ),
    ]
