# Generated by Django 4.0.4 on 2022-05-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0120_alter_reference_study_design_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='study_sample_method',
            field=models.TextField(blank=True, default='', help_text='A description of the sampling method (i.e. how samples were selected and collected) used in the study'),
            preserve_default=False,
        ),
    ]
