# Generated by Django 4.0.4 on 2022-05-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0122_rename_fk_publisher_id_reference_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='publisher_name_alt',
            field=models.CharField(blank=True, default='', help_text='The name of the publisher as provided in the source material, if different than the publisher indicated by publish_id. ', max_length=500),
        ),
    ]
