# Generated by Django 4.0.4 on 2022-05-29 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0123_alter_reference_publisher_name_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='publish_year',
            field=models.CharField(blank=True, default='', help_text='The year in which the study was published', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$')]),
            preserve_default=False,
        ),
    ]
