# Generated by Django 4.0.4 on 2022-05-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0124_alter_reference_publish_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='publish_doi',
            field=models.CharField(blank=True, default='', help_text='The DOI associated with the reference, i.e. 10.3168/jds.2014-8432', max_length=500),
            preserve_default=False,
        ),
    ]
