# Generated by Django 4.0.4 on 2022-05-29 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0125_alter_reference_publish_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='publish_pmid',
            field=models.CharField(blank=True, default='', help_text='The eight-digit PMID associated with the reference, i.e. 84889799', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$')]),
            preserve_default=False,
        ),
    ]
