# Generated by Django 4.0.4 on 2022-05-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0126_alter_reference_publish_pmid'),
    ]

    operations = [
        migrations.CreateModel(
            name='source_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_project_name', models.CharField(max_length=100)),
                ('source_project_user_owner', models.CharField(max_length=50)),
                ('source_project_user_entry', models.CharField(max_length=50)),
                ('source_project_entry_date', models.DateField()),
            ],
        ),
    ]
