# Generated by Django 4.0.4 on 2022-05-29 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0127_source_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_project',
            name='source_project_user_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_user_entry', to='cedar_core.legacy_user'),
        ),
        migrations.AlterField(
            model_name='source_project',
            name='source_project_user_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_user_owner', to='cedar_core.legacy_user'),
        ),
    ]
