# Generated by Django 4.0.4 on 2022-05-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0128_alter_source_project_source_project_user_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='source_project',
            field=models.ForeignKey(blank=b'I01\n', null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.source_project'),
            preserve_default=b'I01\n',
        ),
    ]
