# Generated by Django 4.0.4 on 2022-05-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0129_reference_source_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='source_project',
            name='project_references',
            field=models.ManyToManyField(db_table='source_project_join_reference', related_name='project_references', to='cedar_core.reference'),
        ),
    ]
