# Generated by Django 4.0.4 on 2022-05-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0130_source_project_project_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='source_project',
            name='project_factors',
            field=models.ManyToManyField(db_table='source_project_join_factor', related_name='project_factors', to='cedar_core.factor'),
        ),
    ]
