# Generated by Django 4.0.4 on 2022-05-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0131_source_project_project_factors'),
    ]

    operations = [
        migrations.AddField(
            model_name='source_project',
            name='project_res_outcomes',
            field=models.ManyToManyField(db_table='source_project_join_res_outcome', related_name='project_res_outcomes', to='cedar_core.res_outcome'),
        ),
    ]
