# Generated by Django 4.0.4 on 2022-05-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0132_source_project_project_res_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference_join_location',
            name='hist_join_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='reference_join_location_fix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_detail', models.TextField(blank=True, help_text='A free-text description of the subdivision, allowing users to specify custom subdivisions like "east", "Mid-atlantic region" or "Nationwide"', null=True)),
                ('location_alpha3_dep', models.TextField(blank=True, null=True)),
                ('hist_join_id', models.IntegerField(blank=True, null=True)),
                ('location_main_id', models.ForeignKey(blank=True, db_column='location_main_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_01')),
                ('location_sub_id', models.ForeignKey(blank=True, db_column='location_sub_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_sub')),
                ('reference_id', models.ForeignKey(blank=True, db_column='reference_id', help_text='The reference pertaining to this location', null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference')),
            ],
        ),
    ]
