# Generated by Django 4.0.4 on 2022-05-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0134_delete_reference_join_location_fix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='fk_reference_ast_method_id',
            new_name='ref_ast_method_id',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='ast_free',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='study_location_01_num',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='t2_ast_break',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='t2_ast_breakID',
        ),
    ]
