# Generated by Django 4.0.4 on 2022-06-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0135_rename_fk_reference_ast_method_id_reference_ref_ast_method_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_02',
            name='host_production_stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.production_stream'),
        ),
        migrations.CreateModel(
            name='host_life_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_life_stage_name', models.CharField(max_length=100)),
                ('applies_to_hosts', models.ManyToManyField(db_table='host_life_stage_join_host_level_01', to='cedar_core.host_01')),
            ],
        ),
        migrations.AddField(
            model_name='host_02',
            name='host_production_life_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.host_life_stage'),
        ),
    ]
