# Generated by Django 4.0.4 on 2022-06-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0136_host_02_host_production_stream_host_life_stage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host_02',
            old_name='host_production_life_stage',
            new_name='host_life_stage',
        ),
    ]
