# Generated by Django 4.0.4 on 2022-06-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0138_remove_production_stream_host_subs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production_stream',
            old_name='host_main',
            new_name='host_level_01',
        ),
    ]
