# Generated by Django 4.0.4 on 2022-06-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0140_factor_host_life_stage_factor_host_production_stream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='res_outcome',
            old_name='fk_res_outcome_ast_method_id',
            new_name='ast_method',
        ),
        migrations.RenameField(
            model_name='res_outcome',
            old_name='extract_date_ro',
            new_name='extract_date',
        ),
        migrations.RenameField(
            model_name='res_outcome',
            old_name='fk_extract_res_outcome_user_id',
            new_name='extract_user_legacy',
        ),
        migrations.RenameField(
            model_name='res_outcome',
            old_name='soid',
            new_name='pid',
        ),
    ]
