# Generated by Django 4.0.4 on 2022-06-22 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0141_rename_fk_res_outcome_ast_method_id_res_outcome_ast_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='res_outcome',
            old_name='fk_ast_breakpoint_source_id',
            new_name='ast_breakpoint_source',
        ),
        migrations.RenameField(
            model_name='res_outcome',
            old_name='fk_figure_extract_method_id',
            new_name='figure_extract_method',
        ),
        migrations.RenameField(
            model_name='res_outcome',
            old_name='figure_extract',
            new_name='is_figure_extract',
        ),
        migrations.RemoveField(
            model_name='res_outcome',
            name='breakpoint_explicit',
        ),
        migrations.AddField(
            model_name='res_outcome',
            name='ast_breakpoint_is_explicit',
            field=models.BooleanField(blank=True, help_text='The breakpoint (if explicit, but not from standard breakpoint source).  This field is not necessary to complete if breakpoint source is true. Set to NA if not assessed', null=True),
        ),
        migrations.AddField(
            model_name='res_outcome',
            name='ast_breakpoint_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.ast_breakpoint_version'),
        ),
        migrations.AddField(
            model_name='res_outcome',
            name='extract_project',
            field=models.ForeignKey(blank=True, help_text='The project in which the object was extracted. ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.source_project'),
        ),
    ]
