# Generated by Django 4.0.4 on 2022-06-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0143_rename_fk_factor_id_res_outcome_factor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='fk_group_allocate_production_stage_id',
            new_name='group_allocate_production_stage',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='fk_factor_host_01_id',
            new_name='host_level_01',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='fk_host_02_id',
            new_name='host_level_02',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='sfid',
            new_name='pid_factor',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='fk_factor_reference_id',
            new_name='reference',
        ),
    ]
