# Generated by Django 4.0.4 on 2022-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0144_rename_fk_group_allocate_production_stage_id_factor_group_allocate_production_stage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='exclude_extraction_reason',
            new_name='excluded_extract_reason',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='fk_cedar_exclude_id',
            new_name='excluded_extract_reason_type',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='exclude_model_reason',
            new_name='excluded_model_reason',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='archived',
            new_name='is_archived',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='exclude_extraction',
            new_name='is_excluded_extract',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='exclude_model',
            new_name='is_excluded_model',
        ),
        migrations.AddField(
            model_name='reference',
            name='pid_reference',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
