# Generated by Django 4.0.4 on 2022-06-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0145_rename_exclude_extraction_reason_reference_excluded_extract_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='res_outcome',
            old_name='pid',
            new_name='pid_ro',
        ),
    ]
