# Generated by Django 4.0.4 on 2022-06-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0146_rename_pid_res_outcome_pid_ro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='group_exposed',
            new_name='group_factor',
        ),
    ]
