# Generated by Django 4.0.4 on 2022-06-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0147_rename_group_exposed_factor_group_factor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factor',
            old_name='group_referent',
            new_name='group_comparator',
        ),
    ]
