# Generated by Django 4.0.4 on 2022-06-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0148_rename_group_referent_factor_group_comparator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='fk_study_design_id',
            new_name='study_design',
        ),
    ]
