# Generated by Django 4.0.4 on 2022-06-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0149_rename_fk_study_design_id_reference_study_design'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='ref_ast_method_id',
            new_name='ref_ast_method',
        ),
    ]
