# Generated by Django 4.0.4 on 2022-06-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0150_rename_ref_ast_method_id_reference_ref_ast_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='ref_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_01'),
        ),
    ]
