# Generated by Django 4.0.4 on 2022-07-03 18:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0151_reference_ref_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='exclude_cedar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='factor_description',
            field=models.TextField(blank=True, help_text='A description of the factor.', null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='factor_title',
            field=models.TextField(blank=True, help_text='A title for the factor.', null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='group_comparator',
            field=models.TextField(blank=True, help_text='A brief description of the comparator (i.e., un-exposed, control, referent)  group.', null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='group_factor',
            field=models.TextField(blank=True, help_text='A brief description of the factor (i.e., exposed, case)  group.', null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='host_level_01',
            field=models.ForeignKey(blank=True, help_text='The host (level 1) from which the assayed samples were isolated.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.host_01'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='host_level_02',
            field=models.ForeignKey(blank=True, help_text='The host (level 2) from which the assayed samples were isolated.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.host_02'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='host_life_stage',
            field=models.ForeignKey(help_text='The life stage of the host.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.host_life_stage'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='host_production_stream',
            field=models.ForeignKey(help_text='The production stream of the host.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.production_stream'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='pid_factor',
            field=models.PositiveIntegerField(blank=True, help_text='The physical ID of the factor.', null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='reference',
            field=models.ForeignKey(default=99999, help_text='The reference that reports the factor.', on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='archived_reason',
            field=models.CharField(blank=True, help_text='A reason why the resistance-outcome was archived.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='capture_2019_reject',
            field=models.BooleanField(blank=True, help_text='Where TRUE, the reference was captured in the iAM.AMR.SEARCH_2019 project.', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='capture_search_2016',
            field=models.BooleanField(blank=True, help_text='Where TRUE, the reference was captured in the iAM.AMR.SEARCH_2016 project.', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='capture_search_2019',
            field=models.BooleanField(blank=True, help_text='Where TRUE, the reference was captured in the iAM.AMR.SEARCH_2019 project.', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='excluded_extract_reason',
            field=models.TextField(blank=True, help_text='The reason(s) why the factor was excluded from further data extraction.', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='excluded_extract_reason_type',
            field=models.ForeignKey(blank=True, help_text='The type of reason why the reference was excluded from further data extraction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.cedar_exclude'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, help_text='Where TRUE, the resistance-outcome is archived. ', null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='is_excluded_extract',
            field=models.BooleanField(default=False, help_text='Where TRUE, the factor was excluded from further data extraction.'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publish_year',
            field=models.CharField(blank=True, help_text='The year of reference publication.', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='The publisher of the reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.publisher'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publisher_name_alt',
            field=models.CharField(blank=True, default='', help_text='The name of the publisher at the time of publication, if different from publisher.', max_length=500),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_abstract',
            field=models.TextField(blank=True, help_text='The abstract of the reference.'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_ast_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.ast_method'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_author',
            field=models.TextField(blank=True, help_text='The author(s) of the reference.'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_title',
            field=models.TextField(default='', help_text='The title of the reference.'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='study_design',
            field=models.ForeignKey(blank=True, help_text='The type of study design reported in the reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.study_design'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='study_design_detail',
            field=models.TextField(blank=True, help_text='A description of the study design reported in the reference.'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='study_sample_method',
            field=models.TextField(blank=True, help_text='A description of the sampling method reported in the reference.'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='extract_user_legacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.legacy_user'),
        ),
    ]
