# Generated by Django 4.0.4 on 2022-07-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0152_alter_factor_exclude_cedar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host_01',
            old_name='host_name',
            new_name='host_01_name',
        ),
        migrations.RemoveField(
            model_name='host_01',
            name='cedar_esr_host_01_id',
        ),
    ]
