# Generated by Django 4.0.4 on 2022-07-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0154_rename_cipars_region_atlantic_location_sub_is_cipars_region_atlantic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='source_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.source_project'),
        ),
    ]
