# Generated by Django 4.0.4 on 2022-07-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0155_alter_reference_source_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ast_method',
            old_name='method',
            new_name='ast_method_name',
        ),
    ]
