# Generated by Django 4.0.4 on 2022-07-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0156_rename_method_ast_method_ast_method_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='res_outcome',
            old_name='table_n_exp',
            new_name='table_n_ab',
        ),
        migrations.RenameField(
            model_name='res_outcome',
            old_name='table_n_ref',
            new_name='table_n_cd',
        ),
    ]
