# Generated by Django 4.0.6 on 2022-07-07 17:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0157_rename_table_n_exp_res_outcome_table_n_ab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ast_breakpoint_source',
            name='ast_breakpoint_std',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ast_breakpoint_source',
            name='ast_breakpoint_std_accno',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ast_breakpoint_source',
            name='ast_breakpoint_std_acronym',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ast_breakpoint_source',
            name='ast_breakpoint_std_desc',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ast_breakpoint_version',
            name='ast_breakpoint_std',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ast_breakpoint_version',
            name='ast_breakpoint_version',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ast_breakpoint_version',
            name='clsi_std_type',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ast_breakpoint_version',
            name='date_last_valid',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ast_breakpoint_version',
            name='date_publish',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ast_method',
            name='ast_method_name',
            field=models.CharField(help_text=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='aro_number',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='is_added',
            field=models.BooleanField(help_text=None),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='is_duplicate',
            field=models.BooleanField(help_text=None),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='is_gene',
            field=models.BooleanField(help_text=None),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelcode_1',
            field=models.CharField(blank=True, help_text=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelcode_2',
            field=models.CharField(blank=True, help_text=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelcode_3',
            field=models.CharField(blank=True, help_text=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelcode_4',
            field=models.CharField(blank=True, help_text=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelcode_5',
            field=models.CharField(blank=True, help_text=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_1',
            field=models.CharField(help_text=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_2',
            field=models.CharField(blank=True, help_text=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_3',
            field=models.CharField(blank=True, help_text=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_4',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_4_coarse',
            field=models.CharField(blank=True, help_text=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_5',
            field=models.CharField(blank=True, help_text=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_5_alt',
            field=models.CharField(blank=True, help_text=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atc_vet',
            name='levelname_5_comb_example',
            field=models.CharField(blank=True, help_text=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cedar_exclude',
            name='exclusion',
            field=models.CharField(blank=True, help_text=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cedar_exclude',
            name='exclusion_type',
            field=models.CharField(blank=True, help_text=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='evidence_type_quality',
            name='evidence_type',
            field=models.CharField(blank=True, help_text=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='evidence_type_quality',
            name='evidence_type_accno',
            field=models.CharField(blank=True, help_text=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='evidence_type_quality',
            name='evidence_type_description',
            field=models.TextField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='factor_description',
            field=models.TextField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='factor_title',
            field=models.TextField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='group_allocate_production_stage',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.production_stage'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='group_comparator',
            field=models.TextField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='group_factor',
            field=models.TextField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='host_level_01',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.host_01'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='host_level_02',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.host_02'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='host_life_stage',
            field=models.ForeignKey(help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.host_life_stage'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='host_production_stream',
            field=models.ForeignKey(help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.production_stream'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='pid_factor',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='reference',
            field=models.ForeignKey(default=99999, help_text=None, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference'),
        ),
        migrations.AlterField(
            model_name='factor_family',
            name='factor_family_name',
            field=models.CharField(blank=True, help_text=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='factor_family_join_parent_factor',
            name='fk_family_join_parent_factor_family_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor_family'),
        ),
        migrations.AlterField(
            model_name='factor_family_join_parent_factor',
            name='fk_family_join_parent_factor_parent_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor_parent'),
        ),
        migrations.AlterField(
            model_name='factor_join_res_outcome',
            name='fk_factor_join_res_outcome_factor_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor'),
        ),
        migrations.AlterField(
            model_name='factor_join_res_outcome',
            name='fk_res_outcome_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.res_outcome'),
        ),
        migrations.AlterField(
            model_name='factor_parent',
            name='factor_parent_name',
            field=models.CharField(blank=True, help_text=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_join_atc_vet',
            name='fk_amu_atc_vet_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.atc_vet'),
        ),
        migrations.AlterField(
            model_name='factor_parent_join_atc_vet',
            name='fk_amu_factor_parent_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor_parent'),
        ),
        migrations.AlterField(
            model_name='factor_parent_join_factor',
            name='fk_parent_join_factor_factor_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor'),
        ),
        migrations.AlterField(
            model_name='factor_parent_join_factor',
            name='fk_parent_join_factor_factor_parent_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor_parent'),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='applicable_data_source',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='applicable_data_source_added_year',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='fk_applicable_evidence_type_quality_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_quality_applicability', to='cedar_core.evidence_type_quality'),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='fk_entry_user_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_entry', to='cedar_core.legacy_user'),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='fk_frequency_evidence_type_quality_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_quality_frequency', to='cedar_core.evidence_type_quality'),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='fk_metadata_factor_parent_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.factor_parent'),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='fk_metadata_location_02_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_02'),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='fk_review_user_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_review', to='cedar_core.legacy_user'),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='frequency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='frequency_data_apply_end_year',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='frequency_data_apply_start_year',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='frequency_data_source',
            field=models.CharField(blank=True, help_text=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='frequency_data_source_added_year',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='frequency_distribution',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='frequency_param_a',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='frequency_param_b',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='frequency_param_c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='is_applicable_future',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='is_applicable_past',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='is_applicable_present',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='factor_parent_metadata',
            name='note',
            field=models.TextField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='figure_extract_method',
            name='method_convert_to_count',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='figure_extract_method',
            name='method_description',
            field=models.TextField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='figure_extract_method',
            name='method_name',
            field=models.TextField(blank=True, help_text=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='figure_extract_method',
            name='method_wpd',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='genetic_element',
            name='element_accno',
            field=models.CharField(blank=True, help_text=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='genetic_element',
            name='element_alias',
            field=models.CharField(blank=True, help_text=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='genetic_element',
            name='element_family_accno',
            field=models.CharField(blank=True, help_text=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='genetic_element',
            name='element_name',
            field=models.CharField(blank=True, help_text=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='genetic_element',
            name='element_type',
            field=models.CharField(blank=True, help_text=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='genetic_element',
            name='element_uid',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='genetic_element',
            name='to_review',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='host_01',
            name='host_01_name',
            field=models.CharField(help_text=None, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='host_02',
            name='DEP_sel_beef',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='host_02',
            name='DEP_sel_broil',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='host_02',
            name='host_level_01',
            field=models.ForeignKey(help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.host_01'),
        ),
        migrations.AlterField(
            model_name='host_02',
            name='host_subtype_name',
            field=models.CharField(help_text=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='legacy_user',
            name='cedar_esr_user_id',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='legacy_user',
            name='name_user',
            field=models.CharField(help_text=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='country',
            field=models.CharField(default='N/A', help_text=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='is_developing',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='is_land_lock_least_developed_countries',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='is_least_developed_countries',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='is_small_island_developing_states',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='iso_3166_1_alpha2',
            field=models.CharField(blank=True, help_text=None, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='iso_3166_1_alpha3',
            field=models.CharField(blank=True, help_text=None, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='iso_3166_1_numeric',
            field=models.IntegerField(blank=True, help_text=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='loc_intermediate_subregion_code',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='loc_intermediate_subregion_name',
            field=models.CharField(blank=True, help_text=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='loc_region_code',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='loc_region_name',
            field=models.CharField(blank=True, help_text=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='loc_subregion_code',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='loc_subregion_name',
            field=models.CharField(blank=True, help_text=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location_01',
            name='m49',
            field=models.IntegerField(blank=True, help_text=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location_02',
            name='cipars_region_atlantic',
            field=models.BooleanField(help_text=None),
        ),
        migrations.AlterField(
            model_name='location_02',
            name='cipars_region_maritimes',
            field=models.BooleanField(help_text=None),
        ),
        migrations.AlterField(
            model_name='location_02',
            name='cipars_region_national',
            field=models.BooleanField(help_text=None),
        ),
        migrations.AlterField(
            model_name='location_02',
            name='cipars_region_prairies',
            field=models.BooleanField(help_text=None),
        ),
        migrations.AlterField(
            model_name='location_02',
            name='subdivision',
            field=models.CharField(help_text=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='location_02',
            name='subdivision_type',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location_sub',
            name='is_cipars_region_atlantic',
            field=models.BooleanField(help_text=None),
        ),
        migrations.AlterField(
            model_name='location_sub',
            name='is_cipars_region_maritimes',
            field=models.BooleanField(help_text=None),
        ),
        migrations.AlterField(
            model_name='location_sub',
            name='is_cipars_region_national',
            field=models.BooleanField(help_text=None),
        ),
        migrations.AlterField(
            model_name='location_sub',
            name='is_cipars_region_prairies',
            field=models.BooleanField(help_text=None),
        ),
        migrations.AlterField(
            model_name='location_sub',
            name='iso_3166_1_alpha2',
            field=models.ForeignKey(db_column='iso_3166_1_alpha2', help_text=None, on_delete=django.db.models.deletion.DO_NOTHING, to='cedar_core.location_01', to_field='iso_3166_1_alpha2'),
        ),
        migrations.AlterField(
            model_name='location_sub',
            name='iso_3166_2',
            field=models.CharField(help_text=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='location_sub',
            name='subdivision',
            field=models.CharField(help_text=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='location_sub',
            name='subdivision_type',
            field=models.CharField(blank=True, help_text=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='microbe_01',
            name='microbe_01_name',
            field=models.CharField(help_text=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='microbe_02',
            name='HIST_cedar_esr_microbe_02',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='microbe_02',
            name='microbe_02_name',
            field=models.CharField(help_text=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='microbe_02',
            name='microbe_level_01',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.microbe_01'),
        ),
        migrations.AlterField(
            model_name='moa_type',
            name='moa_type_name',
            field=models.CharField(help_text=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='moa_unit',
            name='outcome_unit_name',
            field=models.CharField(help_text=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='fk_model_create_user_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_c', to='cedar_core.legacy_user'),
        ),
        migrations.AlterField(
            model_name='model',
            name='fk_model_maintain_user_id',
            field=models.ManyToManyField(db_table='model_user_join', help_text=None, to='cedar_core.legacy_user'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_create_date',
            field=models.DateField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_description',
            field=models.CharField(blank=True, help_text=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_maintain_date',
            field=models.DateField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_name',
            field=models.CharField(help_text=None, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='production_stage',
            name='HIST_cedar_esr_production_stage',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='production_stage',
            name='production_stage_name',
            field=models.CharField(help_text=None, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pub_issn',
            field=models.TextField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pub_rank',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pub_title',
            field=models.TextField(help_text=None),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pub_type',
            field=models.CharField(blank=True, help_text=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='archived_reason',
            field=models.CharField(blank=True, help_text=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='capture_2019_reject',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='capture_search_2016',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='capture_search_2019',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='capture_snowball',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='capture_submit',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='cedar_extract_esr',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='cedar_extract_turkey_update',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='excluded_extract_reason',
            field=models.TextField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='excluded_extract_reason_type',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.cedar_exclude'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='excluded_model_reason',
            field=models.CharField(blank=True, help_text=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='fk_reference_status_id',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='is_excluded_extract',
            field=models.BooleanField(default=False, help_text=None),
        ),
        migrations.AlterField(
            model_name='reference',
            name='is_excluded_model',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='key_bibtex',
            field=models.CharField(default='', help_text=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publish_doi',
            field=models.CharField(blank=True, help_text=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publish_pmid',
            field=models.CharField(blank=True, help_text=None, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publish_year',
            field=models.CharField(blank=True, help_text=None, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.publisher'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publisher_name_alt',
            field=models.CharField(blank=True, default='', help_text=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_abstract',
            field=models.TextField(blank=True, help_text=None),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_author',
            field=models.TextField(blank=True, help_text=None),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_has_ast_explicit_break',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No'), ('2', 'Unclear'), ('3', 'Not Reported'), ('4', 'Needs Review')], help_text=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_has_ast_mic_table',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No'), ('2', 'Unclear'), ('3', 'Not Reported'), ('4', 'Needs Review')], help_text=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_has_data_geno_level',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No'), ('2', 'Unclear'), ('3', 'Not Reported'), ('4', 'Needs Review')], help_text=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_has_data_pheno_level',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No'), ('2', 'Unclear'), ('3', 'Not Reported'), ('4', 'Needs Review')], help_text=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_has_esbl_factor',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No'), ('2', 'Unclear'), ('3', 'Not Reported'), ('4', 'Needs Review')], help_text=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ref_title',
            field=models.TextField(default='', help_text=None),
        ),
        migrations.AlterField(
            model_name='reference',
            name='refwk',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='study_design',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.study_design'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='study_design_detail',
            field=models.TextField(blank=True, help_text=None),
        ),
        migrations.AlterField(
            model_name='reference',
            name='study_sample_method',
            field=models.TextField(blank=True, help_text=None),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_campylobacter',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_cattle',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_chicken',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_ecoli',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_enterococcus',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_salmonella',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_swine',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='topic_tab_turkey',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='v12_is_in_v1_and_v2',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='v12_is_v1_import',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='v12_migrated_from',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='v12_migrated_to',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='v12_solo_extraction_2016',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='v12_v1_id',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='v2_fk_m_reference_history_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.reference_join_reference_history'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='v2_fk_reference_history_last_action',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.reference_history_action'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='v2_fk_user_reference_history_last_action',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.legacy_user'),
        ),
        migrations.AlterField(
            model_name='reference_history_action',
            name='action_level_fine',
            field=models.CharField(blank=True, help_text=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_join_location',
            name='location_detail',
            field=models.TextField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference_join_location',
            name='location_main_id',
            field=models.ForeignKey(blank=True, db_column='location_main_id', help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_01'),
        ),
        migrations.AlterField(
            model_name='reference_join_location',
            name='location_sub_id',
            field=models.ForeignKey(blank=True, db_column='location_sub_id', help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.location_sub'),
        ),
        migrations.AlterField(
            model_name='reference_join_location',
            name='reference_id',
            field=models.ForeignKey(blank=True, db_column='reference_id', help_text=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference'),
        ),
        migrations.AlterField(
            model_name='reference_join_reference_history',
            name='reference_join_history_reference_id',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference_join_reference_note',
            name='fk_reference_join_note_reference_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.reference'),
        ),
        migrations.AlterField(
            model_name='reference_join_reference_note',
            name='fk_reference_join_note_user_id',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.legacy_user'),
        ),
        migrations.AlterField(
            model_name='reference_join_reference_note',
            name='is_apply_factor',
            field=models.BooleanField(default=False, help_text=None),
        ),
        migrations.AlterField(
            model_name='reference_join_reference_note',
            name='note',
            field=models.TextField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='reference_join_reference_note',
            name='resolved',
            field=models.BooleanField(default=False, help_text=None),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='ast_breakpoint_is_explicit',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='ast_breakpoint_source',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.ast_breakpoint_source'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='ast_breakpoint_version',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.ast_breakpoint_version'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='ast_method',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.ast_method'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='contable_a',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='contable_b',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='contable_c',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='contable_d',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='extract_date',
            field=models.DateField(default=django.utils.timezone.now, help_text=None),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='extract_project',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.source_project'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='extract_user_legacy',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.legacy_user'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='factor',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.factor'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='factor_v0_id',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='figure_extract_method',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.figure_extract_method'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='figure_extract_reproducible',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='group_observe_production_stage',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.production_stage'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='is_figure_extract',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='microbe_level_01',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.microbe_01'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='microbe_level_02',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.microbe_02'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='moa_type',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.moa_type'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='moa_unit',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.moa_unit'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='odds_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='odds_ratio_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, help_text=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='odds_ratio_lo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='odds_ratio_sig',
            field=models.CharField(blank=True, help_text=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='odds_ratio_up',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='pid_ro',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='place_in_text',
            field=models.TextField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='prevtable_a',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='prevtable_b',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='prevtable_c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='prevtable_d',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='resistance',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.atc_vet'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='resistance_gene',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.genetic_element'),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='table_n_ab',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='table_n_cd',
            field=models.PositiveIntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='v12_ID_factor_v1',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='v12_ID_reference_v1',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='v12_ID_reference_v2_initial',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='v12_is_v1_import',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='v12_solo_extraction_2016',
            field=models.BooleanField(blank=True, help_text=None, null=True),
        ),
        migrations.AlterField(
            model_name='study_design',
            name='study_design_name',
            field=models.CharField(help_text=None, max_length=50, unique=True),
        ),
    ]
