# Generated by Django 4.0.6 on 2022-07-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0162_rename_ast_breakpoint_source_ast_reference_standard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='res_outcome',
            old_name='ast_breakpoint_source',
            new_name='ast_reference_standard',
        ),
        migrations.CreateModel(
            name='ast_reference_standard_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ast_reference_std_version', models.CharField(blank=True, help_text=None, max_length=200, null=True)),
                ('ast_reference_std_pub_year', models.PositiveSmallIntegerField(blank=True, help_text=None)),
                ('clsi_std_doc_name', models.CharField(blank=True, help_text=None, max_length=200, null=True)),
                ('ast_reference_std', models.ForeignKey(help_text=None, on_delete=django.db.models.deletion.CASCADE, to='cedar_core.ast_reference_standard')),
            ],
        ),
        migrations.AlterField(
            model_name='res_outcome',
            name='ast_breakpoint_version',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.ast_reference_standard_version'),
        ),
        migrations.DeleteModel(
            name='ast_breakpoint_version',
        ),
    ]
