# Generated by Django 4.0.6 on 2022-07-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0163_rename_ast_breakpoint_source_res_outcome_ast_reference_standard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='logic_dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic_state', models.CharField(help_text=None, max_length=50, unique=True)),
                ('logic_state_desc', models.TextField(help_text=None)),
                ('logic_state_accurl', models.URLField(help_text=None)),
                ('hist_ref_logic_state', models.CharField(help_text=None, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ast_reference_standard',
            name='ast_reference_std_accno',
            field=models.CharField(blank=True, default='', help_text=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ast_reference_standard',
            name='ast_reference_std_acronym',
            field=models.CharField(blank=True, default='', help_text=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ast_reference_standard',
            name='ast_reference_std_desc',
            field=models.CharField(blank=True, default='', help_text=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ast_reference_standard',
            name='ast_reference_std_name',
            field=models.CharField(default='', help_text=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ast_reference_standard_version',
            name='ast_reference_std_version',
            field=models.CharField(blank=True, default='', help_text=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ast_reference_standard_version',
            name='clsi_std_doc_name',
            field=models.CharField(blank=True, default='', help_text=None, max_length=200),
            preserve_default=False,
        ),
    ]
