# Generated by Django 4.0.6 on 2022-07-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0164_logic_dictionary_and_more'),
    ]

    operations = [

        migrations.RenameField(
            model_name='genetic_element',
            old_name='element_accno',
            new_name='genetic_element_accno',
        ),
        migrations.RenameField(
            model_name='genetic_element',
            old_name='element_alias',
            new_name='genetic_element_alias',
        ),
        migrations.RenameField(
            model_name='genetic_element',
            old_name='element_family_accno',
            new_name='genetic_element_family_accno',
        ),
        migrations.RenameField(
            model_name='genetic_element',
            old_name='element_name',
            new_name='genetic_element_name',
        ),
        migrations.RenameField(
            model_name='genetic_element',
            old_name='element_type',
            new_name='genetic_element_type',
        ),
        migrations.RemoveField(
            model_name='genetic_element',
            name='element_uid',
        ),
        migrations.RemoveField(
            model_name='genetic_element',
            name='to_review',
        ),
        
    ]
