# Generated by Django 4.0.6 on 2022-07-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0165_remove_genetic_element_element_accno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetic_element',
            name='genetic_element_accno',
            field=models.CharField(blank=True, default='', help_text=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genetic_element',
            name='genetic_element_alias',
            field=models.CharField(blank=True, default='', help_text=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genetic_element',
            name='genetic_element_family_accno',
            field=models.CharField(blank=True, default='', help_text=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genetic_element',
            name='genetic_element_name',
            field=models.CharField(default='', help_text=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genetic_element',
            name='genetic_element_type',
            field=models.CharField(default='', help_text=None, max_length=200),
            preserve_default=False,
        ),
    ]
