# Generated by Django 4.0.6 on 2022-07-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0166_alter_genetic_element_genetic_element_accno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='ref_has_data_geno_level',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='ref_has_data_pheno_level',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='ref_has_esbl_factor',
        ),
        migrations.AddField(
            model_name='reference',
            name='has_ast_explicit_break',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ast_explicit_break', to='cedar_core.logic_dictionary'),
        ),
        migrations.AddField(
            model_name='reference',
            name='has_ast_mic_table',
            field=models.ForeignKey(blank=True, help_text=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ast_mic_table', to='cedar_core.logic_dictionary'),
        ),
    ]
