# Generated by Django 4.0.6 on 2022-07-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0167_remove_reference_ref_has_data_geno_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='ref_has_ast_explicit_break',
            new_name='hist_ref_has_ast_explicit_break',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='ref_has_ast_mic_table',
            new_name='hist_ref_has_ast_mic_table',
        ),
    ]
