# Generated by Django 4.0.6 on 2022-07-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0169_rename_has_ast_explicit_break_reference_ref_has_ast_explicit_break_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ast_method',
            name='hist_ast_method_id',
            field=models.IntegerField(blank=True, help_text=None),
        ),
    ]
