# Generated by Django 4.0.6 on 2022-07-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0170_alter_ast_method_hist_ast_method_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ast_method',
            name='hist_ast_method_id',
            field=models.IntegerField(blank=True, help_text=None, null=True),
        ),
    ]
