# Generated by Django 4.1 on 2022-09-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0171_alter_ast_method_hist_ast_method_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference_join_reference_note',
            old_name='is_apply_factor',
            new_name='is_factor_note',
        ),
        migrations.RenameField(
            model_name='reference_join_reference_note',
            old_name='resolved',
            new_name='is_resolved',
        ),
        migrations.RenameField(
            model_name='reference_join_reference_note',
            old_name='fk_reference_join_note_reference_id',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='reference_join_reference_note',
            old_name='note',
            new_name='reference_note',
        ),
        migrations.RenameField(
            model_name='reference_join_reference_note',
            old_name='fk_reference_join_note_user_id',
            new_name='user',
        ),
    ]
