# Generated by Django 4.1 on 2022-09-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0172_rename_is_apply_factor_reference_join_reference_note_is_factor_note_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reference_join_reference_note',
            new_name='reference_note',
        ),
    ]
