# Generated by Django 4.2.1 on 2023-08-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0173_rename_reference_join_reference_note_reference_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference_note',
            name='is_factor_note',
        ),
    ]
