# Generated by Django 4.2.1 on 2023-08-13 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cedar_core', '0001_squashed_0175_alter_ast_method_ast_method_accno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='ref_ast_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cedar_core.ast_method_old'),
        ),
    ]
